/**
 * vendor-manifests — runtime allowlist loader.
 *
 * Reads each vendor/<name>/urls.md (auto-generated by scripts/crawl-vendors.ts)
 * to build an in-memory allowlist + URL→relPath index. Cached after first
 * load. Re-loadable via `reloadVendorManifests()` (used by tests).
 *
 * Citations:
 *   @cite seeds/posture/session-start.xml
 *   @cite vendor/anthropics/code.claude.com/docs/en/commands.md
 *
 * Read-only; no fetches.
 */
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
// src/lib/ → repo root is two levels up. Allow KE_VENDOR_DIR override
// for installed-package consumers (per the plan's risk note about
// rootDir excluding vendor/ from dist/).
const REPO_ROOT = resolve(__dirname, "..", "..");
const VENDOR_ROOT = process.env.KE_VENDOR_DIR ?? resolve(REPO_ROOT, "vendor");

export interface VendorManifest {
  name: string;
  llms_txt?: string;
  lastCrawled?: Date;
  /** Set of canonical URLs the runtime allows. */
  urlSet: Set<string>;
  /** Index from URL to vendor-relative mirror path (e.g. "docs.stripe.com/api/charges.md"). */
  byUrl: Map<string, string>;
}

let CACHE: ReadonlyMap<string, VendorManifest> | null = null;

function listVendorDirs(): string[] {
  if (!existsSync(VENDOR_ROOT)) return [];
  return readdirSync(VENDOR_ROOT, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(resolve(VENDOR_ROOT, e.name, "urls.md")))
    .map((e) => e.name)
    .sort();
}

function parseUrlsMd(name: string, body: string): VendorManifest {
  const llmsTxtMatch = body.match(/^llms_txt:\s*(.+?)\s*$/m);
  const lastMatch = body.match(/^last_crawled:\s*(.+?)\s*$/m);
  const llms_txt = llmsTxtMatch?.[1];
  const lastRaw = lastMatch?.[1];
  const lastCrawled = lastRaw ? new Date(lastRaw) : undefined;

  const urlSet = new Set<string>();
  const byUrl = new Map<string, string>();
  // Each row: "| <url> | `vendor/<name>/<relpath>` |"
  const ROW_RE = /^\|\s*([^|\s]\S*)\s*\|\s*`vendor\/[^/]+\/(.+?)`\s*\|/gm;
  for (const m of body.matchAll(ROW_RE)) {
    const url = m[1];
    const relPath = m[2];
    if (!url || !relPath || !url.startsWith("http")) continue;
    urlSet.add(url);
    byUrl.set(url, relPath);
  }

  const out: VendorManifest = { name, urlSet, byUrl };
  if (llms_txt !== undefined) out.llms_txt = llms_txt;
  if (lastCrawled !== undefined) out.lastCrawled = lastCrawled;
  return out;
}

export function loadVendorManifests(): ReadonlyMap<string, VendorManifest> {
  if (CACHE !== null) return CACHE;
  const out = new Map<string, VendorManifest>();
  for (const name of listVendorDirs()) {
    const path = resolve(VENDOR_ROOT, name, "urls.md");
    const body = readFileSync(path, "utf8");
    out.set(name, parseUrlsMd(name, body));
  }
  CACHE = out;
  return out;
}

export function reloadVendorManifests(): ReadonlyMap<string, VendorManifest> {
  CACHE = null;
  return loadVendorManifests();
}

export function getVendor(name: string): VendorManifest | undefined {
  return loadVendorManifests().get(name);
}

export function vendorRoot(): string {
  return VENDOR_ROOT;
}
