// servers/npm-registry/npm_org_packages.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * List all packages owned by an npm organization. Returns name + role per package. Source: https://www.npmjs.com/org/{org}/package.
 *
 * MCP tool: npm-registry__npm_org_packages
 */
export async function npmOrgPackages(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("npm-registry__npm_org_packages", input);
}
