// servers/npm-registry/npm_search.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Full-text search the npm registry. Returns up to `size` results with name, description, and score. Source: https://registry.npmjs.org/-/v1/search.
 *
 * MCP tool: npm-registry__npm_search
 */
export async function npmSearch(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("npm-registry__npm_search", input);
}
