// servers/npm-registry/npm_package_metadata.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Fetch a package document from the npm registry: versions, dist-tags, maintainers, latest manifest. Source: https://registry.npmjs.org/{package}.
 *
 * MCP tool: npm-registry__npm_package_metadata
 */
export async function npmPackageMetadata(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("npm-registry__npm_package_metadata", input);
}
