// servers/npm-registry/npm_downloads.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Download counts for a package over a window (last-day | last-week | last-month). Source: https://api.npmjs.org/downloads/point/{period}/{package}.
 *
 * MCP tool: npm-registry__npm_downloads
 */
export async function npmDownloads(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("npm-registry__npm_downloads", input);
}
