// servers/knowledge-bridge/blog_fetch.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Fetch a specific Claude blog post. Accepts a full https://www.claude.com/blog/<slug> URL or the slug alone. Mirror-first; falls back to live HTTP.
 *
 * MCP tool: knowledge-bridge__blog_fetch
 */
export async function blogFetch(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__blog_fetch", input);
}
