// servers/knowledge-bridge/blog_index.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * List posts on https://www.claude.com/blog. Returns title + url for each post discovered on the index page.
 *
 * MCP tool: knowledge-bridge__blog_index
 */
export async function blogIndex(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__blog_index", input);
}
