// servers/knowledge-bridge/blog_search.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Text-match the Claude blog index titles. Case-insensitive substring search.
 *
 * MCP tool: knowledge-bridge__blog_search
 */
export async function blogSearch(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__blog_search", input);
}
