// servers/knowledge-bridge/engineering_fetch.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Fetch a specific engineering post. Accepts either a full https://www.anthropic.com/engineering/<slug> URL or the slug alone. Mirror-first: returns local body when present (source:'mirror'), else falls back to live HTTP (source:'http').
 *
 * MCP tool: knowledge-bridge__engineering_fetch
 */
export async function engineeringFetch(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__engineering_fetch", input);
}
