// servers/knowledge-bridge/engineering_search.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Text-match the engineering index titles. Case-insensitive substring search; returns the matching entries.
 *
 * MCP tool: knowledge-bridge__engineering_search
 */
export async function engineeringSearch(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__engineering_search", input);
}
