// servers/knowledge-bridge/llms_namespaces.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * List the curated set of llms.txt namespaces this bridge knows about.
 *
 * MCP tool: knowledge-bridge__llms_namespaces
 */
export async function llmsNamespaces(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__llms_namespaces", input);
}
