// servers/knowledge-bridge/llms_fetch.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Fetch one llms.txt namespace and return its raw text. `id` is one of the values returned by `llms_namespaces` (e.g. 'code.claude.com/docs').
 *
 * MCP tool: knowledge-bridge__llms_fetch
 */
export async function llmsFetch(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__llms_fetch", input);
}
