// servers/knowledge-bridge/llms_grep.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Case-insensitive line-grep across every known llms.txt namespace. Mirror-first per namespace (no HTTP if the body is in vendor/<name>/llms.txt mirror) — Phase 4 speed win. Returns each hit with its source URL.
 *
 * MCP tool: knowledge-bridge__llms_grep
 */
export async function llmsGrep(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__llms_grep", input);
}
