// servers/knowledge-bridge/project_find_files.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Walk the project tree (skipping node_modules, .git, dist, .terraform, coverage, .cache, .next) and return files matching an optional substring pattern + optional size constraints. Replaces Bash(`find ...`) + `stat` chains at no shell-spawn cost.
 *
 * MCP tool: knowledge-bridge__project_find_files
 */
export async function projectFindFiles(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__project_find_files", input);
}
