// servers/knowledge-bridge/project_git_status.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Report git working-tree status as structured JSON. Replaces Bash(`git status --porcelain`) at roughly half the token cost. Use to detect drift before committing or pushing.
 *
 * MCP tool: knowledge-bridge__project_git_status
 */
export async function projectGitStatus(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__project_git_status", input);
}
