// servers/knowledge-bridge/project_git_log.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * List recent commits as structured JSON (sha, subject, author, timestamp). Replaces Bash(`git log --pretty=...`) at roughly a third the token cost. `since` accepts any git revspec ('HEAD~10', 'origin/main..HEAD', '2026-05-01').
 *
 * MCP tool: knowledge-bridge__project_git_log
 */
export async function projectGitLog(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__project_git_log", input);
}
