// servers/knowledge-bridge/search_tools.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Progressive-disclosure tool discovery for the codemode runtime. Searches across servers/<name>/README.md catalogs and returns matching tools with their qualified names + (optional) descriptions. Use this to find tools by capability instead of loading every tool definition into context up front. Cited from platform.claude.com/docs/en/agents-and-tools/tool-use/programmatic-tool-calling.md.
 *
 * MCP tool: knowledge-bridge__search_tools
 */
export async function searchTools(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__search_tools", input);
}
