// servers/knowledge-bridge/support_article.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Fetch a specific support article. Accepts a full https://support.claude.com/en/articles/<id-slug> URL or the bare '<id>-<slug>' fragment. Mirror-first; allowlist-enforced HTTP fallback (rejects URLs outside support.claude.com/en/articles/).
 *
 * MCP tool: knowledge-bridge__support_article
 */
export async function supportArticle(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__support_article", input);
}
