// servers/knowledge-bridge/support_search.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Text-match support.claude.com article titles against the local mirror manifest. Returns URL + slug-derived title for each hit, no HTTP required. Sourced from vendor/claude-support/urls.md (341 EN articles).
 *
 * MCP tool: knowledge-bridge__support_search
 */
export async function supportSearch(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__support_search", input);
}
