// servers/knowledge-bridge/support_collection.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Fetch a collection page and return the article links it lists. `slug` is e.g. '14445694-claude-code'.
 *
 * MCP tool: knowledge-bridge__support_collection
 */
export async function supportCollection(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__support_collection", input);
}
