// servers/knowledge-bridge/support_collections.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * List the curated set of support.claude.com collection slugs we recognize. Each entry is the slug used by the bridge tools.
 *
 * MCP tool: knowledge-bridge__support_collections
 */
export async function supportCollections(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__support_collections", input);
}
