// servers/knowledge-bridge/vendor_list.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * List the vendors mirrored under vendor/. Each entry includes the discovered llms.txt URL, last crawl timestamp, and the count of URLs in the runtime allowlist.
 *
 * MCP tool: knowledge-bridge__vendor_list
 */
export async function vendorList(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__vendor_list", input);
}
