// servers/knowledge-bridge/vendor_grep.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Case-insensitive line-grep across the local vendor mirror. Optionally restrict to one vendor. Returns each hit with the vendor, original URL, mirror-relative path, line number, and the matching line.
 *
 * MCP tool: knowledge-bridge__vendor_grep
 */
export async function vendorGrep(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__vendor_grep", input);
}
