// servers/knowledge-bridge/vendor_fetch.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * Fetch a vendor doc by URL. Returns local mirror body when available (source:'mirror'); otherwise falls back to live HTTP (source:'http'). The URL must be in some vendor's allowlist (see vendor_list).
 *
 * MCP tool: knowledge-bridge__vendor_fetch
 */
export async function vendorFetch(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("knowledge-bridge__vendor_fetch", input);
}
