/**
 * Bridge lane: search_tools (Phase 6 — progressive-disclosure tool surface).
 *
 * Implements the "code execution with MCP" pattern from
 * vendor/anthropics/platform.claude.com/docs/en/agents-and-tools/tool-use/programmatic-tool-calling.md
 * — instead of loading every MCP tool definition into the model's context
 * up front, the agent discovers tools on demand via this single tool.
 *
 * Reads from servers/<server>/README.md (auto-generated by
 * scripts/generate-server-tree.ts), which lists every tool with its
 * one-line description.
 *
 * Tools:
 *   search_tools - text-match across all generated tool catalogs.
 *                  Returns name + (optional) description per the
 *                  `detail` parameter.
 */
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { jsonResult } from "../bridge-utils.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..", "..", "..");
const SERVERS_DIR = process.env.KE_SERVERS_DIR ?? resolve(REPO_ROOT, "servers");

interface ToolEntry {
  server: string;
  name: string;
  description: string;
}

let CACHE: ReadonlyArray<ToolEntry> | null = null;

function loadCatalog(): ReadonlyArray<ToolEntry> {
  if (CACHE !== null) return CACHE;
  if (!existsSync(SERVERS_DIR)) {
    CACHE = [];
    return CACHE;
  }
  const out: ToolEntry[] = [];
  for (const entry of readdirSync(SERVERS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const readme = resolve(SERVERS_DIR, entry.name, "README.md");
    if (!existsSync(readme)) continue;
    const body = readFileSync(readme, "utf8");
    // Each tool row: "| `<name>` | <description> |"
    const ROW_RE = /^\|\s*`([^`]+)`\s*\|\s*([^|]+?)\s*\|\s*$/gm;
    for (const m of body.matchAll(ROW_RE)) {
      const name = m[1];
      const desc = m[2];
      if (!name || !desc) continue;
      out.push({ server: entry.name, name, description: desc.trim() });
    }
  }
  CACHE = out;
  return CACHE;
}

export function registerSearchTools(server: McpServer): void {
  server.tool(
    "search_tools",
    "Progressive-disclosure tool discovery for the codemode runtime. Searches across servers/<name>/README.md catalogs and returns matching tools with their qualified names + (optional) descriptions. Use this to find tools by capability instead of loading every tool definition into context up front. Cited from platform.claude.com/docs/en/agents-and-tools/tool-use/programmatic-tool-calling.md.",
    {
      query: z.string().min(1).describe("Substring to match against tool names + descriptions (case-insensitive)."),
      detail: z.enum(["name", "name+description"]).default("name+description").describe("How much of each match to return."),
      limit: z.number().int().positive().max(100).default(20),
    },
    async ({ query, detail, limit }) => {
      const needle = query.toLowerCase();
      const all = loadCatalog();
      const hits = all
        .filter((t) => t.name.toLowerCase().includes(needle) || t.description.toLowerCase().includes(needle))
        .slice(0, limit)
        .map((t) => {
          const qualified = `${t.server}__${t.name}`;
          if (detail === "name") return { name: qualified };
          return { name: qualified, description: t.description };
        });
      return jsonResult({ query, hits, total_indexed: all.length });
    }
  );
}
