/**
 * Pure functions for the redis-queue-design skill.
 *
 * Generates typed Redis key-namespace declarations and a matching
 * Zod-free TypeScript schema for queue entries. The operator describes
 * the queue shape; this module emits the typed contract and usage docs.
 *
 * Refs: ODEP7.
 */

// ---------------------------------------------------------------------------
// Queue spec
// ---------------------------------------------------------------------------

/** Redis data structures this chassis uses. */
export type RedisStructure = "stream" | "list" | "sorted-set" | "hash" | "string";

/** One field in a queue entry's value shape. */
export interface QueueEntryField {
  name: string;
  type: "string" | "number" | "boolean" | "iso8601" | "json";
  optional?: boolean;
  description?: string;
}

export interface QueueSpec {
  /** Logical name, PascalCase. E.g. "CoworkerSessionEvent". */
  name: string;
  /** Redis key pattern. E.g. "coworker:sessions:new". */
  keyPattern: string;
  structure: RedisStructure;
  /** Fields in each entry/message. */
  fields: QueueEntryField[];
  outcomeId: string;
  /** Max size hint for MAXLEN / LTRIM. Optional. */
  maxLen?: number;
}

// ---------------------------------------------------------------------------
// TypeScript emitter
// ---------------------------------------------------------------------------

const TS_FIELD_TYPE: Record<QueueEntryField["type"], string> = {
  string: "string",
  number: "number",
  boolean: "boolean",
  iso8601: "string",
  json: "unknown",
};

export function fieldToTsLine(field: QueueEntryField): string {
  const tsType = TS_FIELD_TYPE[field.type];
  const optional = field.optional ? "?" : "";
  const comment = field.description ? `  // ${field.description}` : "";
  return `  ${field.name}${optional}: ${tsType};${comment}`;
}

export function buildQueueTypeScript(spec: QueueSpec): string {
  const fields = spec.fields.map(fieldToTsLine).join("\n");

  return [
    `// src/domain/queues/${spec.name}.ts`,
    `// Auto-generated by redis-queue-design skill (${spec.outcomeId}).`,
    ``,
    `/** Key pattern: \`${spec.keyPattern}\` (${spec.structure}) */`,
    `export const ${spec.name.toUpperCase()}_KEY = "${spec.keyPattern}" as const;`,
    ``,
    `export interface ${spec.name} {`,
    fields,
    `}`,
    ``,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Redis command reference emitter
// ---------------------------------------------------------------------------

const COMMANDS: Record<RedisStructure, { write: string; read: string; trim: string }> = {
  stream:     { write: "XADD",   read: "XREAD / XREADGROUP", trim: "XTRIM MAXLEN ~" },
  list:       { write: "LPUSH",  read: "BRPOP / RPOPLPUSH",  trim: "LTRIM 0 <maxLen>" },
  "sorted-set": { write: "ZADD", read: "ZRANGEBYSCORE",      trim: "ZREMRANGEBYRANK 0 <maxLen>" },
  hash:       { write: "HSET",   read: "HGETALL",            trim: "n/a (delete fields)" },
  string:     { write: "SET",    read: "GET",                 trim: "n/a (TTL via EXPIRE)" },
};

export function buildQueueMarkdown(spec: QueueSpec): string {
  const cmds = COMMANDS[spec.structure];
  const lines: string[] = [
    `# Queue Design — ${spec.name}`,
    ``,
    `_Outcome: ${spec.outcomeId} · structure: ${spec.structure} · key: \`${spec.keyPattern}\`_`,
    ``,
    `## Redis command surface`,
    ``,
    `| Operation | Command |`,
    `|---|---|`,
    `| Write | \`${cmds.write}\` |`,
    `| Read  | \`${cmds.read}\` |`,
    `| Trim  | \`${cmds.trim}${spec.maxLen ? ` ${spec.maxLen}` : ""}\` |`,
    ``,
    `## Entry schema`,
    ``,
    "```ts",
    buildQueueTypeScript(spec),
    "```",
  ];
  return lines.join("\n");
}
