#!/usr/bin/env tsx
/**
 * gen-pr-queue.ts — render the open-PR queue to docs/pending-prs.md.
 *
 * Groups by mergeStateStatus so the operator can see at a glance:
 *   - READY-CLEAN  : up-to-date, all checks green → about to merge
 *   - READY-BEHIND : needs rebase (OAUTO2 covers automerge-labeled
 *                    ones; others may be intentional)
 *   - READY-DIRTY  : merge conflict → human review needed
 *   - READY-OTHER  : pending/blocked/unknown → CI running
 *   - DRAFT        : not for review yet
 *
 * Usage:
 *   npm run gen:pr-queue        — writes docs/pending-prs.md
 *
 * @cite docs/followups/2026-05-17-merge-velocity-audit.md
 */
import { execFileSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { writeFileSync } from "node:fs";

interface Pr {
  number: number;
  title: string;
  isDraft: boolean;
  mergeStateStatus: string;
  updatedAt: string;
  labels: { name: string }[];
  headRefName: string;
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUT = resolve(REPO_ROOT, "docs/pending-prs.md");

function fetchPRs(): Pr[] {
  const json = execFileSync(
    "gh",
    [
      "pr",
      "list",
      "--state",
      "open",
      "--limit",
      "50",
      "--json",
      "number,title,isDraft,mergeStateStatus,updatedAt,labels,headRefName",
    ],
    { encoding: "utf8", cwd: REPO_ROOT }
  );
  return JSON.parse(json);
}

function ageMinutes(iso: string): number {
  return Math.floor((Date.now() - Date.parse(iso)) / 60_000);
}

function ageStr(min: number): string {
  if (min < 60) return `${min}m`;
  if (min < 60 * 24) return `${Math.floor(min / 60)}h`;
  return `${Math.floor(min / (60 * 24))}d`;
}

function bucketOf(pr: Pr): string {
  if (pr.isDraft) return "DRAFT";
  switch (pr.mergeStateStatus) {
    case "CLEAN":
      return "READY-CLEAN";
    case "BEHIND":
      return "READY-BEHIND";
    case "DIRTY":
      return "READY-DIRTY";
    case "BLOCKED":
    case "UNKNOWN":
    case "UNSTABLE":
    case "HAS_HOOKS":
    default:
      return "READY-OTHER";
  }
}

function row(pr: Pr): string {
  const age = ageStr(ageMinutes(pr.updatedAt));
  const labels = pr.labels.map((l) => l.name).join(",") || "—";
  const t = pr.title.length > 80 ? pr.title.slice(0, 77) + "…" : pr.title;
  return `| [#${pr.number}](https://github.com/subagentceo/knowledge-engineering/pull/${pr.number}) | ${t} | \`${pr.mergeStateStatus}\` | ${age} | ${labels} |`;
}

function section(title: string, prs: Pr[]): string {
  if (prs.length === 0) {
    return `### ${title} (0)\n\n_none_\n`;
  }
  const header = `### ${title} (${prs.length})\n\n| # | Title | State | Updated | Labels |\n| --- | --- | --- | --- | --- |`;
  const rows = prs
    .sort((a, b) => Date.parse(b.updatedAt) - Date.parse(a.updatedAt))
    .map(row)
    .join("\n");
  return `${header}\n${rows}\n`;
}

function main(): void {
  const prs = fetchPRs();
  const buckets = new Map<string, Pr[]>();
  for (const pr of prs) {
    const b = bucketOf(pr);
    if (!buckets.has(b)) buckets.set(b, []);
    buckets.get(b)!.push(pr);
  }

  const order = ["READY-CLEAN", "READY-BEHIND", "READY-OTHER", "READY-DIRTY", "DRAFT"];
  const now = new Date().toISOString();
  const lines: string[] = [
    "# Pending PRs — merge-train dashboard",
    "",
    `_Generated by \`npm run gen:pr-queue\` at ${now}._`,
    "",
    `Total open: **${prs.length}**`,
    "",
    "## Glossary",
    "",
    "- **READY-CLEAN** — up-to-date with main and all required checks green. About to merge.",
    "- **READY-BEHIND** — needs rebase. `automerge`-labeled ones are auto-rebased by `.github/workflows/auto-rebase.yml` (OAUTO2).",
    "- **READY-OTHER** — pending/blocked/unknown; CI is running or a non-merge-related block exists.",
    "- **READY-DIRTY** — merge conflict; human review required.",
    "- **DRAFT** — not yet ready for review.",
    "",
  ];
  for (const b of order) {
    lines.push(section(b, buckets.get(b) ?? []));
    lines.push("");
  }
  for (const [b, prs] of buckets) {
    if (!order.includes(b)) {
      lines.push(section(b, prs));
      lines.push("");
    }
  }
  writeFileSync(OUT, lines.join("\n"));
  console.log(`wrote ${OUT} — ${prs.length} open PR(s)`);
}

main();
