#!/usr/bin/env tsx
// scripts/generate-server-tree.ts
//
// Phase 6.A. Spawns each stdio MCP server this repo ships, sends
// JSON-RPC `tools/list`, and emits one TypeScript file per tool under
//   servers/<server-name>/<tool-name>.ts
// Each emitted file is a thin wrapper around `callMCPTool('<server>__<tool>', input)`.
//
// Citations:
//   @cite vendor/anthropics/platform.claude.com/docs/en/agents-and-tools/tool-use/programmatic-tool-calling.md
//   @cite vendor/anthropics/platform.claude.com/docs/en/agents-and-tools/tool-use/build-a-tool-using-agent.md
//
// Wired as `npm run gen:servers`. CI guard (in lint chain) re-runs this
// and fails if `git diff --exit-code servers/` shows drift.

import { spawn } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { assertOAuthOnly } from "../src/oauth/token.js";

assertOAuthOnly();

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const SERVERS_DIR = resolve(REPO_ROOT, "servers");

interface ServerSpec {
  name: string;
  entry: string;
}

const SERVERS: ServerSpec[] = [
  { name: "knowledge-bridge", entry: resolve(REPO_ROOT, "dist/mcp/bridge-server.js") },
  { name: "npm-registry", entry: resolve(REPO_ROOT, "dist/mcp/npm-registry/server.js") },
];

interface ToolDef {
  name: string;
  description?: string;
  inputSchema?: { properties?: Record<string, unknown>; required?: string[] };
}

async function listTools(spec: ServerSpec): Promise<ToolDef[]> {
  if (!existsSync(spec.entry)) throw new Error(`${spec.entry} missing — run 'npm run build' first.`);

  const child = spawn("node", [spec.entry], { stdio: ["pipe", "pipe", "inherit"] });

  const initialize = {
    jsonrpc: "2.0" as const, id: 1, method: "initialize",
    params: { protocolVersion: "2024-11-05", capabilities: {}, clientInfo: { name: "gen-servers", version: "0.1.0" } },
  };
  const initialized = { jsonrpc: "2.0" as const, method: "notifications/initialized", params: {} };
  const list = { jsonrpc: "2.0" as const, id: 2, method: "tools/list", params: {} };

  child.stdin.write(JSON.stringify(initialize) + "\n");
  child.stdin.write(JSON.stringify(initialized) + "\n");
  child.stdin.write(JSON.stringify(list) + "\n");

  const output = await new Promise<string>((res, rej) => {
    let buf = "";
    const t = setTimeout(() => { child.kill(); rej(new Error(`timeout listing tools for ${spec.name}`)); }, 8000);
    child.stdout.on("data", (chunk) => {
      buf += chunk.toString();
      // Look for the response to id:2.
      for (const line of buf.split("\n")) {
        try {
          const obj = JSON.parse(line);
          if (obj.id === 2 && obj.result?.tools) { clearTimeout(t); child.kill(); res(line); }
        } catch { /* not a complete JSON line yet */ }
      }
    });
    child.on("exit", () => { /* may exit normally after kill */ });
  });

  const obj = JSON.parse(output);
  return obj.result.tools as ToolDef[];
}

function tsIdent(name: string): string {
  // Convert snake_case to camelCase; numbers preserved.
  return name.replace(/_(\w)/g, (_, c) => c.toUpperCase()).replace(/[^A-Za-z0-9]/g, "");
}

function fileFor(server: string, tool: ToolDef): string {
  const fnName = tsIdent(tool.name);
  const desc = (tool.description ?? "").trim().replace(/\*\//g, "*​/").slice(0, 600);
  return `// servers/${server}/${tool.name}.ts
//
// AUTO-GENERATED by scripts/generate-server-tree.ts.
// Re-run 'npm run gen:servers' after any tool surface change.
import { callMCPTool } from "../_client.js";

/**
 * ${desc || "(no description)"}
 *
 * MCP tool: ${server}__${tool.name}
 */
export async function ${fnName}(input: Record<string, unknown> = {}): Promise<unknown> {
  return callMCPTool("${server}__${tool.name}", input);
}
`;
}

function indexFor(server: string, tools: ToolDef[]): string {
  const exports = tools
    .map((t) => `export { ${tsIdent(t.name)} } from "./${t.name}.js";`)
    .join("\n");
  return `// servers/${server}/index.ts
//
// AUTO-GENERATED. Barrel export for the ${server} server's tool wrappers.
${exports}
`;
}

function readmeFor(server: string, tools: ToolDef[]): string {
  const rows = tools
    .map((t) => `| \`${t.name}\` | ${(t.description ?? "(no description)").split("\n")[0].slice(0, 120)} |`)
    .join("\n");
  return `# servers/${server}/

AUTO-GENERATED catalog. Re-run \`npm run gen:servers\` after any tool surface change.

| Tool | Description |
|---|---|
${rows}

Each entry is a thin wrapper around \`callMCPTool("${server}__<tool>", input)\`. The actual MCP server lives at the corresponding \`src/mcp/\` path; this tree is the **filesystem-tree tool API** the codemode runtime imports from.
`;
}

function clientShim(): string {
  return `// servers/_client.ts
//
// AUTO-GENERATED placeholder for the codemode runtime's tool dispatcher.
//
// In Phase 6.B (codemode wiring in src/agent/run.ts), this is replaced
// at runtime by @cloudflare/codemode's DynamicWorkerExecutor — the
// generated wrappers all call into the same callMCPTool symbol.
//
// In Phase 6.A this is a stub that throws. The wrappers compile and
// can be type-checked, but invoking one without the codemode runtime
// raises a clear error.
export async function callMCPTool(qualifiedName: string, input: Record<string, unknown>): Promise<unknown> {
  throw new Error(
    \`callMCPTool stub: tried to invoke \${qualifiedName} (input keys: \${Object.keys(input).join(",")}) without a runtime. \` +
    \`Phase 6.B wires @cloudflare/codemode's DynamicWorkerExecutor as the dispatcher.\`
  );
}
`;
}

async function main(): Promise<void> {
  if (existsSync(SERVERS_DIR)) {
    rmSync(SERVERS_DIR, { recursive: true, force: true });
  }
  mkdirSync(SERVERS_DIR, { recursive: true });
  writeFileSync(resolve(SERVERS_DIR, "_client.ts"), clientShim());

  const counts: Record<string, number> = {};
  for (const spec of SERVERS) {
    const tools = await listTools(spec);
    counts[spec.name] = tools.length;
    const dir = resolve(SERVERS_DIR, spec.name);
    mkdirSync(dir, { recursive: true });
    for (const tool of tools) {
      writeFileSync(resolve(dir, `${tool.name}.ts`), fileFor(spec.name, tool));
    }
    writeFileSync(resolve(dir, "index.ts"), indexFor(spec.name, tools));
    writeFileSync(resolve(dir, "README.md"), readmeFor(spec.name, tools));
  }

  console.log("gen:servers — emitted servers/ tree:");
  for (const [name, n] of Object.entries(counts)) {
    console.log(`  ${name.padEnd(20)} ${n} tool(s)`);
  }
}

main().catch((err) => { console.error(err); process.exit(1); });
